# Generated by Django 4.2.3 on 2023-07-22 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Professor',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('last_CEMEP_date', models.DateField()),
                ('valid_until', models.DateField()),
            ],
            options={
                'abstract': False,
            },
            bases=('accounts.user',),
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='car',
        ),
        migrations.RemoveField(
            model_name='profesor',
            name='user_ptr',
        ),
        migrations.AlterField(
            model_name='user',
            name='user_type',
            field=models.CharField(choices=[('student', 'Student'), ('professor', 'Professor'), ('seller', 'Seller')], max_length=10),
        ),
    ]
