# Generated by Django 4.2.3 on 2023-07-22 17:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30)),
                ('profesor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.profesor')),
            ],
        ),
    ]
