# Generated by Django 4.2.3 on 2023-07-23 06:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0003_delete_profesor_professor_car'),
    ]

    operations = [
        migrations.CreateModel(
            name='EvaluationType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Evaluation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_date', models.DateField(auto_now_add=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('approved', models.BooleanField()),
                ('eval_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='evaluations.evaluationtype')),
                ('professor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.professor')),
                ('student', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student')),
            ],
        ),
    ]
