# Generated by Django 4.1.4 on 2023-07-23 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic_classes_manager', '0002_alter_routes_coordinates'),
    ]

    operations = [
        migrations.AlterField(
            model_name='routes',
            name='description',
            field=models.TextField(),
        ),
    ]
