# Generated by Django 4.1.4 on 2023-07-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profesor_professor_car'),
        ('practic_classes_manager', '0003_alter_routes_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practic_classes',
            name='professor',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.professor'),
        ),
        migrations.AlterField(
            model_name='practic_classes',
            name='route',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='practic_classes_manager.routes'),
        ),
        migrations.AlterField(
            model_name='practic_classes',
            name='seller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='accounts.seller'),
        ),
    ]
