# Generated by Django 4.1.4 on 2023-08-03 01:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('practic_classes_manager', '0005_alter_practic_classes_class_hour'),
    ]

    operations = [
        migrations.AlterField(
            model_name='practic_classes',
            name='attended',
            field=models.BooleanField(default=False),
        ),
    ]
