# Generated by Django 4.1.4 on 2023-08-10 05:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('practic_classes_manager', '0006_alter_practic_classes_attended'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='practic_classes',
            name='route',
        ),
        migrations.DeleteModel(
            name='Routes',
        ),
    ]
