# Generated by Django 4.1.4 on 2023-07-23 19:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_delete_profesor_professor_car'),
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sale',
            name='student',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.student'),
        ),
    ]
