# Generated by Django 4.1.4 on 2023-08-05 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teoric_content_manager', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pdffile',
            name='image',
            field=models.ImageField(null=True, upload_to='images_files/'),
        ),
    ]
